/**
 * API example
 * The API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AppApi", () => {
  let instance: api.AppApi
  beforeEach(function() {
    instance = new api.AppApi(config)
  });

  test("appControllerGetHello", () => {
    return expect(instance.appControllerGetHello({})).resolves.toBe(null)
  })
})

describe("ExamplesApi", () => {
  let instance: api.ExamplesApi
  beforeEach(function() {
    instance = new api.ExamplesApi(config)
  });

  test("exampleControllerCreate", () => {
    const body: api.ExampleDto = undefined
    return expect(instance.exampleControllerCreate(body, {})).resolves.toBe(null)
  })
  test("exampleControllerDelete", () => {
    const key: string = "key_example"
    return expect(instance.exampleControllerDelete(key, {})).resolves.toBe(null)
  })
  test("exampleControllerGet", () => {
    const key: string = "key_example"
    return expect(instance.exampleControllerGet(key, {})).resolves.toBe(null)
  })
  test("exampleControllerList", () => {
    return expect(instance.exampleControllerList({})).resolves.toBe(null)
  })
  test("exampleControllerUpdate", () => {
    const body: api.ExampleDto = undefined
    const key: string = "key_example"
    return expect(instance.exampleControllerUpdate(body, key, {})).resolves.toBe(null)
  })
})

